#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

echo "==> Running eslint"
./node_modules/.bin/eslint .

echo "==> Building"
./scripts/build

echo "==> Checking types"
./node_modules/typescript/bin/tsc

echo "==> Running Are The Types Wrong?"
NPM_CONFIG_CACHE=/private/tmp/unlayer-sdk-npm-cache ./node_modules/.bin/attw --pack dist

echo "==> Running publint"
./node_modules/.bin/publint dist
