#!/usr/bin/env node

const fs = require('node:fs');
const path = require('node:path');

const sdkPath = path.join(__dirname, '..', 'src', 'sdk.gen.ts');
const clientIndexPath = path.join(__dirname, '..', 'src', 'client', 'index.ts');
let source = fs.readFileSync(sdkPath, 'utf8');
let clientIndexSource = fs.readFileSync(clientIndexPath, 'utf8');

const optionsPattern = /> = Options2<TData, ThrowOnError, TResponse> & \{/g;
const responseStylePattern = /^\s+responseStyle: 'data',\n/gm;
const optionsSpreadPattern = /^(\s+)\.\.\.options,?\n/gm;

const optionsMatches = source.match(optionsPattern) ?? [];
const responseStyleMatches = source.match(responseStylePattern) ?? [];
const optionsSpreadMatches = source.match(optionsSpreadPattern) ?? [];

if (optionsMatches.length !== 1) {
  throw new Error(`Expected one generated SDK Options alias, found ${optionsMatches.length}`);
}

if (responseStyleMatches.length === 0 || responseStyleMatches.length !== optionsSpreadMatches.length) {
  throw new Error('Generated SDK request layout changed; refusing to apply unsafe contract fixes');
}

source = source.replace(
  optionsPattern,
  "> = Omit<Options2<TData, ThrowOnError, TResponse>, 'responseStyle' | 'throwOnError'> & {",
);
source = source.replace(responseStylePattern, '');
source = source.replace(
  optionsSpreadPattern,
  (_, indentation) =>
    `${indentation}...options,\n` +
    `${indentation}throwOnError: true as ThrowOnError,\n` +
    `${indentation}responseStyle: 'data',\n`,
);
source = source.replace(/[ \t]+$/gm, '');

const clientHeader = '// This file is auto-generated by @hey-api/openapi-ts\n\n';
const createClientExport = "export { createClient } from './client.gen';";

if (!clientIndexSource.startsWith(clientHeader)) {
  throw new Error('Generated client entry header changed; refusing to apply Unlayer defaults');
}

if (clientIndexSource.split(createClientExport).length !== 2) {
  throw new Error('Expected one generated createClient export');
}

clientIndexSource = clientIndexSource.replace(
  clientHeader,
  `${clientHeader}import { createClient as createHeyApiClient } from './client.gen';\n` +
    "import type { Config as ClientConfig } from './types.gen';\n\n",
);
clientIndexSource = clientIndexSource.replace(
  createClientExport,
  `export const createClient = (config: ClientConfig = {}) =>\n` +
    `  createHeyApiClient({\n` +
    `    ...config,\n` +
    `    baseUrl: config.baseUrl ?? 'https://api.unlayer.com',\n` +
    `    throwOnError: config.throwOnError ?? true,\n` +
    `  });`,
);

fs.writeFileSync(sdkPath, source);
fs.writeFileSync(clientIndexPath, clientIndexSource);
process.stdout.write(
  `Applied SDK contracts to ${responseStyleMatches.length} operations and configured createClient\n`,
);
