#!/usr/bin/env node

const fs = require('node:fs');
const path = require('node:path');

const sdkPath = path.join(__dirname, '..', 'src', 'sdk.gen.ts');
const clientIndexPath = path.join(__dirname, '..', 'src', 'client', 'index.ts');
let source = fs.readFileSync(sdkPath, 'utf8');
let clientIndexSource = fs.readFileSync(clientIndexPath, 'utf8');

source = source.replace(/[ \t]+$/gm, '');

const optionsPattern = /> = Options2<TData, ThrowOnError, TResponse> & \{/g;
const responseStylePattern = /^\s+responseStyle: 'data',\n/gm;
const optionsSpreadPattern = /^(\s+)\.\.\.options,?\n/gm;
const defaultClientImport = "import { client } from './client.gen';\n";
const generatedClientBase = `class HeyApiClient {
    protected client: Client;

    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}
`;
const explicitClientBase = `class HeyApiClient {
    protected client: Client;

    constructor(args: {
        client: Client;
    }) {
        if (!args?.client) {
            throw new TypeError('A client created with createClient() is required.');
        }
        this.client = args.client;
    }
}
`;
const generatedRegistry = `class HeyApiRegistry<T> {
    private readonly defaultKey = 'default';

    private readonly instances: Map<string, T> = new Map();

    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(\`No SDK client found. Create one with "new Unlayer()" to fix this error.\`);
        }
        return instance;
    }

    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

`;
const generatedUnlayerConstructor = `export class Unlayer extends HeyApiClient {
    public static readonly __registry: HeyApiRegistry<Unlayer> = new HeyApiRegistry<Unlayer>();

    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        Unlayer.__registry.set(this, args?.key);
    }
`;
const explicitUnlayerConstructor = `export class Unlayer extends HeyApiClient {
    constructor(args: {
        client: Client;
    }) {
        super(args);
    }
`;

const optionsMatches = source.match(optionsPattern) ?? [];
const responseStyleMatches = source.match(responseStylePattern) ?? [];
const optionsSpreadMatches = source.match(optionsSpreadPattern) ?? [];

if (optionsMatches.length !== 1) {
  throw new Error(`Expected one generated SDK Options alias, found ${optionsMatches.length}`);
}

if (responseStyleMatches.length === 0 || responseStyleMatches.length !== optionsSpreadMatches.length) {
  throw new Error('Generated SDK request layout changed; refusing to apply unsafe contract fixes');
}

for (const [label, generatedFragment] of [
  ['default client import', defaultClientImport],
  ['generated client base', generatedClientBase],
  ['generated registry', generatedRegistry],
  ['generated Unlayer constructor', generatedUnlayerConstructor],
]) {
  if (source.split(generatedFragment).length !== 2) {
    throw new Error(`Expected one ${label}; refusing to expose generated global client state`);
  }
}

source = source.replace(
  optionsPattern,
  "> = Omit<Options2<TData, ThrowOnError, TResponse>, 'responseStyle' | 'throwOnError'> & {",
);
source = source.replace(responseStylePattern, '');
source = source.replace(
  optionsSpreadPattern,
  (_, indentation) =>
    `${indentation}...options,\n` +
    `${indentation}throwOnError: true as ThrowOnError,\n` +
    `${indentation}responseStyle: 'data',\n`,
);
source = source.replace(defaultClientImport, '');
source = source.replace(generatedClientBase, explicitClientBase);
source = source.replace(generatedRegistry, '');
source = source.replace(generatedUnlayerConstructor, explicitUnlayerConstructor);
const clientHeader = '// This file is auto-generated by @hey-api/openapi-ts\n\n';
const createClientExport = "export { createClient } from './client.gen';";

if (!clientIndexSource.startsWith(clientHeader)) {
  throw new Error('Generated client entry header changed; refusing to apply Unlayer defaults');
}

if (clientIndexSource.split(createClientExport).length !== 2) {
  throw new Error('Expected one generated createClient export');
}

clientIndexSource = clientIndexSource.replace(
  clientHeader,
  `${clientHeader}import { createClient as createHeyApiClient } from './client.gen';\n` +
    "import type { Config as ClientConfig } from './types.gen';\n\n",
);
clientIndexSource = clientIndexSource.replace(
  createClientExport,
  `export const createClient = (config: ClientConfig = {}) =>\n` +
    `  createHeyApiClient({\n` +
    `    ...config,\n` +
    `    baseUrl: config.baseUrl ?? 'https://api.unlayer.com',\n` +
    `    throwOnError: config.throwOnError ?? true,\n` +
    `  });`,
);

fs.writeFileSync(sdkPath, source);
fs.writeFileSync(clientIndexPath, clientIndexSource);
process.stdout.write(
  `Applied SDK contracts to ${responseStyleMatches.length} operations, removed global client state, and configured createClient\n`,
);
