// This file is auto-generated by @hey-api/openapi-ts

import { createClient as createHeyApiClient } from './client.gen';
import type { Config as ClientConfig } from './types.gen';

export type { Auth } from '../core/auth.gen';
export type { QuerySerializerOptions } from '../core/bodySerializer.gen';
export {
  formDataBodySerializer,
  jsonBodySerializer,
  urlSearchParamsBodySerializer,
} from '../core/bodySerializer.gen';
export { buildClientParams } from '../core/params.gen';
export { serializeQueryKeyValue } from '../core/queryKeySerializer.gen';
export type { ServerSentEventsResult } from '../core/serverSentEvents.gen';
export type { ClientMeta } from '../core/types.gen';
export const createClient = (config: ClientConfig = {}) =>
  createHeyApiClient({
    ...config,
    baseUrl: config.baseUrl ?? 'https://api.unlayer.com',
    throwOnError: config.throwOnError ?? true,
  });
export type {
  Client,
  ClientOptions,
  Config,
  CreateClientConfig,
  Options,
  RequestOptions,
  RequestResult,
  ResolvedRequestOptions,
  ResponseStyle,
  TDataShape,
} from './types.gen';
export { createConfig, mergeHeaders } from './utils.gen';
